import { useState } from 'react';
import { HiCalendar, HiPlus, HiX, HiSparkles, HiCheckCircle } from 'react-icons/hi';
import toast from 'react-hot-toast';
import api from '@/services/api';

export default function AIStudyPlan() {
  const [form, setForm] = useState({
    examName: '',
    targetDate: '',
    hoursPerDay: 3,
    weakTopics: [],
    strongTopics: [],
  });
  const [topicInput, setTopicInput] = useState({ weak: '', strong: '' });
  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(false);

  const addTopic = (type) => {
    const val = topicInput[type].trim();
    if (!val) return;
    setForm((f) => ({ ...f, [`${type}Topics`]: [...f[`${type}Topics`], val] }));
    setTopicInput((t) => ({ ...t, [type]: '' }));
  };

  const removeTopic = (type, idx) =>
    setForm((f) => ({ ...f, [`${type}Topics`]: f[`${type}Topics`].filter((_, i) => i !== idx) }));

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!form.examName || !form.targetDate) {
      toast.error('Exam name and date required');
      return;
    }
    setLoading(true);
    setPlan(null);
    try {
      const { data } = await api.post('/ai/study-plan', form);
      setPlan(data.data);
      toast.success('Study plan created!');
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to generate plan');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-8">
      <div className="flex items-center gap-3">
        <div className="h-10 w-10 rounded-2xl bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center">
          <HiCalendar className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
        </div>
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900 dark:text-white">AI Study Plan</h1>
          <p className="text-sm text-slate-600 dark:text-slate-400">
            Personalized exam prep plan generated by AI
          </p>
        </div>
      </div>

      <form
        onSubmit={handleGenerate}
        className="bg-white dark:bg-dark-800 rounded-2xl border border-slate-100 dark:border-dark-700 p-6 space-y-5"
      >
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="sm:col-span-2">
            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
              Exam Name *
            </label>
            <input
              className="w-full px-4 py-2.5 rounded-xl border border-slate-200 dark:border-dark-600 bg-slate-50 dark:bg-dark-900 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
              placeholder="e.g. JEE Main, UPSC, CAT"
              value={form.examName}
              onChange={(e) => setForm((f) => ({ ...f, examName: e.target.value }))}
            />
          </div>
          <div>
            <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
              Exam Date *
            </label>
            <input
              type="date"
              className="w-full px-4 py-2.5 rounded-xl border border-slate-200 dark:border-dark-600 bg-slate-50 dark:bg-dark-900 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
              min={new Date().toISOString().split('T')[0]}
              value={form.targetDate}
              onChange={(e) => setForm((f) => ({ ...f, targetDate: e.target.value }))}
            />
          </div>
        </div>

        <div>
          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
            Study hours per day: {form.hoursPerDay}h
          </label>
          <input
            type="range"
            min={1}
            max={12}
            value={form.hoursPerDay}
            onChange={(e) => setForm((f) => ({ ...f, hoursPerDay: parseInt(e.target.value) }))}
            className="w-full accent-emerald-500"
          />
        </div>

        {/* Weak topics */}
        <div>
          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
            Weak Topics (need more time)
          </label>
          <div className="flex gap-2 mb-2">
            <input
              className="flex-1 px-4 py-2 rounded-xl border border-slate-200 dark:border-dark-600 bg-slate-50 dark:bg-dark-900 text-sm"
              placeholder="e.g. Trigonometry"
              value={topicInput.weak}
              onChange={(e) => setTopicInput((t) => ({ ...t, weak: e.target.value }))}
              onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addTopic('weak'))}
            />
            <button
              type="button"
              onClick={() => addTopic('weak')}
              className="px-3 py-2 rounded-xl bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400 hover:bg-red-200"
            >
              <HiPlus className="h-4 w-4" />
            </button>
          </div>
          <div className="flex flex-wrap gap-2">
            {form.weakTopics.map((t, i) => (
              <span
                key={i}
                className="flex items-center gap-1 px-3 py-1 rounded-full bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-300 text-xs font-medium"
              >
                {t}{' '}
                <button type="button" onClick={() => removeTopic('weak', i)}>
                  <HiX className="h-3 w-3" />
                </button>
              </span>
            ))}
          </div>
        </div>

        {/* Strong topics */}
        <div>
          <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
            Strong Topics (quick review)
          </label>
          <div className="flex gap-2 mb-2">
            <input
              className="flex-1 px-4 py-2 rounded-xl border border-slate-200 dark:border-dark-600 bg-slate-50 dark:bg-dark-900 text-sm"
              placeholder="e.g. Algebra"
              value={topicInput.strong}
              onChange={(e) => setTopicInput((t) => ({ ...t, strong: e.target.value }))}
              onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addTopic('strong'))}
            />
            <button
              type="button"
              onClick={() => addTopic('strong')}
              className="px-3 py-2 rounded-xl bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-200"
            >
              <HiPlus className="h-4 w-4" />
            </button>
          </div>
          <div className="flex flex-wrap gap-2">
            {form.strongTopics.map((t, i) => (
              <span
                key={i}
                className="flex items-center gap-1 px-3 py-1 rounded-full bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 text-xs font-medium"
              >
                {t}{' '}
                <button type="button" onClick={() => removeTopic('strong', i)}>
                  <HiX className="h-3 w-3" />
                </button>
              </span>
            ))}
          </div>
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full py-3 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-sm transition-all disabled:opacity-60 flex items-center justify-center gap-2"
        >
          {loading ? (
            <>
              <span className="h-4 w-4 border-2 border-white/40 border-t-white rounded-full animate-spin" />{' '}
              Generating...
            </>
          ) : (
            <>
              <HiSparkles className="h-4 w-4" /> Generate Study Plan
            </>
          )}
        </button>
      </form>

      {plan && (
        <div className="space-y-6">
          <div className="bg-emerald-50 dark:bg-emerald-900/20 rounded-2xl border border-emerald-200 dark:border-emerald-800 p-6">
            <h2 className="text-lg font-bold text-emerald-900 dark:text-emerald-100 mb-1">
              Your Plan — {plan.examName}
            </h2>
            <p className="text-emerald-700 dark:text-emerald-300 text-sm">{plan.plan?.overview}</p>
            <p className="text-emerald-600 dark:text-emerald-400 text-sm mt-2 font-medium">
              Daily Goal: {plan.plan?.dailyGoal}
            </p>
            <p className="text-emerald-500 text-xs mt-1">{plan.daysLeft} days remaining</p>
          </div>

          {plan.plan?.weeklyPlan?.map((week) => (
            <div
              key={week.week}
              className="bg-white dark:bg-dark-800 rounded-2xl border border-slate-100 dark:border-dark-700 p-6"
            >
              <h3 className="text-base font-bold text-slate-900 dark:text-white mb-4">
                Week {week.week}: {week.theme}
              </h3>
              <div className="space-y-2">
                {week.days?.map((day, i) => (
                  <div
                    key={i}
                    className="flex items-start gap-3 p-3 rounded-xl bg-slate-50 dark:bg-dark-900"
                  >
                    <HiCheckCircle
                      className={`h-4 w-4 mt-0.5 flex-shrink-0 ${day.priority === 'high' ? 'text-red-500' : day.priority === 'medium' ? 'text-amber-500' : 'text-emerald-500'}`}
                    />
                    <div className="flex-1 min-w-0">
                      <span className="text-sm font-semibold text-slate-700 dark:text-slate-300">
                        {day.day}
                      </span>
                      <span className="text-xs text-slate-600 dark:text-slate-400 ml-2">
                        ({day.duration}h)
                      </span>
                      <div className="flex flex-wrap gap-1.5 mt-1">
                        {day.topics?.map((t, ti) => (
                          <span
                            key={ti}
                            className="px-2 py-0.5 rounded-full bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300 text-xs"
                          >
                            {t}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}

          {plan.plan?.tips?.length > 0 && (
            <div className="bg-white dark:bg-dark-800 rounded-2xl border border-slate-100 dark:border-dark-700 p-6">
              <h3 className="text-base font-bold text-slate-900 dark:text-white mb-3">
                Study Tips
              </h3>
              <ul className="space-y-2">
                {plan.plan.tips.map((tip, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-300"
                  >
                    <span className="text-emerald-500 mt-0.5">✓</span> {tip}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
