export const mockExams = [
  {
    _id: 'exam-1',
    slug: 'patwari',
    name: 'Patwari',
    category: 'Rajasthan',
    description: 'Patwari recruitment exam for Rajasthan',
    syllabus: 'General Knowledge, Mathematics, Hindi, English',
    pattern: '150 questions, 3 hours',
    eligibility: 'Graduation',
    importantDates: 'Application: Jan 2024, Exam: Mar 2024',
    courses: ['course-1', 'course-2'],
    testSeries: ['test-series-1'],
    resources: ['resource-1'],
    blogs: ['blog-1', 'blog-2'],
    jobAlerts: ['job-1'],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'exam-2',
    slug: 'ras',
    name: 'RAS (Rajasthan Administrative Service)',
    category: 'Rajasthan',
    description: 'RAS exam for administrative services',
    syllabus: 'History, Geography, Polity, Economy',
    pattern: 'Prelims + Mains',
    eligibility: 'Graduation',
    importantDates: 'Notification: Feb 2024',
    courses: ['course-3'],
    testSeries: ['test-series-2'],
    resources: ['resource-2'],
    blogs: ['blog-3'],
    jobAlerts: [],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'exam-3',
    slug: 'political-science',
    name: 'Political Science',
    category: 'Political Science',
    description: 'Political Science for various exams',
    syllabus: 'Political Theory, Indian Politics, International Relations',
    pattern: 'Varies by exam',
    eligibility: 'Graduation',
    importantDates: 'Varies',
    courses: ['course-4'],
    testSeries: [],
    resources: [],
    blogs: [],
    jobAlerts: [],
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockCourses = [
  {
    _id: 'course-1',
    title: 'Target Patwari Batch 2024',
    slug: 'target-patwari-batch-2024',
    shortDescription: 'Complete Patwari preparation',
    description: 'Comprehensive course for Patwari exam',
    price: 4999,
    originalPrice: 9999,
    discount: 50,
    level: 'beginner',
    language: 'Hindi',
    examCategory: 'exam-1',
    examCategoryName: 'Patwari',
    faculty: { name: 'Dr. Sharma', avatar: '/faculty/sharma.jpg' },
    modules: [
      {
        _id: 'mod-1',
        title: 'General Knowledge',
        lessons: [{ _id: 'lesson-1', title: 'Rajasthan History', duration: 45, isFree: true }],
      },
      {
        _id: 'mod-2',
        title: 'Mathematics',
        lessons: [{ _id: 'lesson-2', title: 'Arithmetic', duration: 60, isFree: false }],
      },
    ],
    thumbnail: '/courses/patwari.jpg',
    isPublished: true,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 120,
    enrollmentCount: 5000,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'course-2',
    title: 'Patwari Crash Course',
    slug: 'patwari-crash-course',
    shortDescription: 'Quick revision for Patwari',
    description: 'Last minute preparation',
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    level: 'intermediate',
    language: 'Hindi',
    examCategory: 'exam-1',
    examCategoryName: 'Patwari',
    faculty: { name: 'Prof. Singh', avatar: '/faculty/singh.jpg' },
    modules: [
      {
        _id: 'mod-3',
        title: 'Quick Revision',
        lessons: [{ _id: 'lesson-3', title: 'Important Topics', duration: 30, isFree: true }],
      },
    ],
    thumbnail: '/courses/patwari-crash.jpg',
    isPublished: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 45,
    enrollmentCount: 1200,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'course-3',
    title: 'RAS Foundation Course',
    slug: 'ras-foundation-course',
    shortDescription: 'Complete RAS preparation',
    description: 'Foundation course for RAS',
    price: 14999,
    originalPrice: 24999,
    discount: 40,
    level: 'beginner',
    language: 'English',
    examCategory: 'exam-2',
    examCategoryName: 'RAS',
    faculty: { name: 'Dr. Gupta', avatar: '/faculty/gupta.jpg' },
    modules: [
      {
        _id: 'mod-4',
        title: 'History',
        lessons: [{ _id: 'lesson-4', title: 'Ancient India', duration: 90, isFree: true }],
      },
    ],
    thumbnail: '/courses/ras.jpg',
    isPublished: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 200,
    enrollmentCount: 3000,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockTestSeries = [
  {
    _id: 'test-series-1',
    title: 'Patwari Mock Test Series 2024',
    slug: 'patwari-mock-test-series-2024',
    description: '10 full-length mock tests',
    examCategory: 'exam-1',
    examCategoryName: 'Patwari',
    tests: ['test-1', 'test-2', 'test-3'],
    price: 999,
    originalPrice: 1999,
    discount: 50,
    isPublished: true,
    testCount: 10,
    enrollmentCount: 3000,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'test-series-2',
    title: 'RAS Mock Test Series',
    slug: 'ras-mock-test-series',
    description: '15 full-length mock tests',
    examCategory: 'exam-2',
    examCategoryName: 'RAS',
    tests: ['test-4', 'test-5'],
    price: 1999,
    originalPrice: 3999,
    discount: 50,
    isPublished: true,
    testCount: 15,
    enrollmentCount: 1500,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockTests = [
  {
    _id: 'test-1',
    title: 'Patwari Mock Test 01',
    slug: 'patwari-mock-test-01',
    testSeries: 'test-series-1',
    testSeriesTitle: 'Patwari Mock Test Series 2024',
    description: 'Full length mock test',
    duration: 180,
    totalQuestions: 150,
    totalMarks: 150,
    negativeMarking: 0.25,
    allowedAttempts: 1,
    status: 'published',
    questions: [
      {
        _id: 'q1',
        questionText: 'Capital of Rajasthan?',
        type: 'MCQ',
        options: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota'],
        correctAnswer: 'Jaipur',
        marks: 1,
        sectionName: 'General Knowledge',
      },
      {
        _id: 'q2',
        questionText: '2 + 2 = ?',
        type: 'MCQ',
        options: ['3', '4', '5', '6'],
        correctAnswer: '4',
        marks: 1,
        sectionName: 'Mathematics',
      },
    ],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'test-2',
    title: 'Patwari Mock Test 02',
    slug: 'patwari-mock-test-02',
    testSeries: 'test-series-1',
    testSeriesTitle: 'Patwari Mock Test Series 2024',
    description: 'Full length mock test',
    duration: 180,
    totalQuestions: 150,
    totalMarks: 150,
    negativeMarking: 0.25,
    allowedAttempts: 1,
    status: 'published',
    questions: [],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockResources = [
  {
    _id: 'resource-1',
    title: 'Patwari PYQ 2023',
    slug: 'patwari-pyq-2023',
    description: 'Previous year question paper',
    examCategory: 'exam-1',
    examCategoryName: 'Patwari',
    type: 'PYQ',
    isFree: true,
    fileUrl: '/resources/patwari-pyq-2023.pdf',
    thumbnail: '/resources/pyq.jpg',
    downloadCount: 5000,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'resource-2',
    title: 'RAS Syllabus PDF',
    slug: 'ras-syllabus-pdf',
    description: 'Official syllabus',
    examCategory: 'exam-2',
    examCategoryName: 'RAS',
    type: 'SYLLABUS',
    isFree: true,
    fileUrl: '/resources/ras-syllabus.pdf',
    thumbnail: '/resources/syllabus.jpg',
    downloadCount: 2000,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockBlogs = [
  {
    _id: 'blog-1',
    title: 'Patwari Preparation Strategy 2024',
    slug: 'patwari-preparation-strategy-2024',
    content: 'Detailed strategy for Patwari exam...',
    excerpt: 'How to prepare for Patwari exam effectively',
    examCategory: 'exam-1',
    examCategoryName: 'Patwari',
    type: 'article',
    author: 'Expert Team',
    thumbnail: '/blogs/patwari-strategy.jpg',
    isPublished: true,
    publishedAt: '2024-01-15T00:00:00Z',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    _id: 'blog-2',
    title: 'Patwari Recruitment 2026 Notification',
    slug: 'patwari-recruitment-2026-notification',
    content: 'Official notification details...',
    excerpt: 'Patwari recruitment notification released',
    examCategory: 'exam-1',
    examCategoryName: 'Patwari',
    type: 'job_alert',
    author: 'Official Source',
    thumbnail: '/blogs/patwari-job.jpg',
    isPublished: true,
    publishedAt: '2024-02-01T00:00:00Z',
    recruitmentDates: { start: '2024-02-01', end: '2024-03-01' },
    officialLink: 'https://example.com/patwari-notification',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const mockUsers = {
  student: {
    _id: 'user-student-1',
    name: 'Arjun Student',
    email: 'arjun@student.com',
    role: 'student',
    avatar: '/avatars/arjun.jpg',
    enrolledCourses: ['course-1'],
    purchasedTestSeries: ['test-series-1'],
    bookmarks: ['resource-1'],
  },
  teacher: {
    _id: 'user-teacher-1',
    name: 'Teacher User',
    email: 'teacher@civicsedu.com',
    role: 'teacher',
    avatar: '/avatars/teacher.jpg',
  },
  admin: {
    _id: 'user-admin-1',
    name: 'Admin User',
    email: 'admin@civicsedu.com',
    role: 'admin',
    avatar: '/avatars/admin.jpg',
  },
};

export const mockAuthTokens = {
  student: 'mock-student-token',
  teacher: 'mock-teacher-token',
  admin: 'mock-admin-token',
};

export const mockEnrollment = {
  _id: 'enrollment-1',
  user: 'user-student-1',
  course: 'course-1',
  status: 'active',
  progressPercentage: 45,
  completedLessons: ['lesson-1'],
  lastAccessedLesson: 'lesson-2',
  enrolledAt: '2024-01-15T00:00:00Z',
  updatedAt: '2024-02-01T00:00:00Z',
};

export const mockTestAttempt = {
  _id: 'attempt-1',
  user: 'user-student-1',
  test: 'test-1',
  testSeries: 'test-series-1',
  status: 'completed',
  score: 120,
  totalMarks: 150,
  correctAnswers: 125,
  incorrectAnswers: 15,
  unattemptedQuestions: 10,
  accuracy: 83.33,
  timeTaken: 90,
  startedAt: '2024-02-01T10:00:00Z',
  submittedAt: '2024-02-01T11:30:00Z',
  answers: [
    { questionId: 'q1', selectedOption: 'Jaipur', isCorrect: true, marksObtained: 1 },
    { questionId: 'q2', selectedOption: '4', isCorrect: true, marksObtained: 1 },
  ],
};
